### ISSUE TITLE
Conversion didn't finish normally, the resulting world may not be playable.

### ISSUE THREAD

**Issue by CHJ85** [minetest-tools/mcimport#24]
I keep seeing this message.
Tried to convert 10 saves. Some are very basic. So this is odd.
They all show this message and none of them are playable.
Am I doing something wrong? Are any other software required?
Very little documentation here.

**Comment by sofar** [comment]
What's the full console output? What os did you use? What mc version is this map from?

**Comment by CHJ85** [comment]
Ubuntu. And sorry, I forgot to provide the output:

WARNING:block:Unknown Minecraft Block:175:1s
WARNING:block:Unknown Minecraft Block:175:8
WARNING:block:Unknown Minecraft Block:175:4s
WARNING:block:Unknown Minecraft Block:175:8
Traceback (most recent call last):1:23 h:m:s
  File "mcimport.py", line 107, in <module>
    mtmap.save()
  File "/home/chris/Downloads/mcimport-master/block.py", line 455, in save
    for block in self.blocks:
  File "/home/chris/Downloads/mcimport-master/block.py", line 439, in fromMCMapBlocksIterator
    for mcblock in mcmap.getBlocksIterator():
  File "/home/chris/Downloads/mcimport-master/block.py", line 62, in getBlocksIterator
    blocks = self.getChunk(chkx, chkz).blocks
  File "/home/chris/Downloads/mcimport-master/block.py", line 45, in getChunk
    return MCChunk(chkx, chkz, self.world_path, self.ext)
  File "/home/chris/Downloads/mcimport-master/block.py", line 86, in __init__
    raw_data = nbt.read(udata)['']['Level']
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 51, in read
    return _read_named(bytes, 0)[0]
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 47, in _read_named
    value, index = _read_tag(bytes, index, tag)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 35, in _read_tag
    return _read_named(bytes, index)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 47, in _read_named
    value, index = _read_tag(bytes, index, tag)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 35, in _read_tag
    return _read_named(bytes, index)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 47, in _read_named
    value, index = _read_tag(bytes, index, tag)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 35, in _read_tag
    return _read_named(bytes, index)
  File "/home/chris/Downloads/mcimport-master/nbt.py", line 47, in _read_named
    value, index = _read_tag(bytes, index, tag)
TypeError: cannot unpack non-iterable NoneType object

**Comment by CHJ85** [comment]
Any idea why this could be?

**Comment by sofar** [comment]
Bug in code. Unfortunately really deep in the `nbt` parser that I don't know of a fix.

What MC version was used to make this map?

**Comment by CHJ85** [comment]
Not sure. Didn't make it myself. I only download maps.
Could the problem here be that the minetest mods are not in my local home directory?
I installed them with Synaptic, so they're in /usr/share/games/minetest.

**Comment by Ekdohibs** [comment]
I just pushed a change that might at least partially solve the issue, could you try it to see what you get? The problem is unrelated to mods not being in the local home directory, it is instead related to Minecraft having probably updated the save format.

**Comment by CHJ85** [comment]
Thanks, but no luck.
I tried downloading the original map from the planetminecraft site. This worked somewhat.
The conversion was a success according to the script.
But an init.lua file was missing:
2019-08-29 12:06:37: WARNING[Main]: BanManager: creating /home/chris/.minetest/worlds/House/ipban.txt
2019-08-29 12:06:37: ERROR[Main]: ModError: Failed to load and run script from /home/chris/.minetest/worlds/House/worldmods/mesecons/init.lua:
2019-08-29 12:06:37: ERROR[Main]: /home/chris/.minetest/worlds/House/worldmods/mesecons/init.lua: No such file or directory

**Comment by Ekdohibs** [comment]
Hmmm that's another problem. Did you try to run get-mods.sh script?

**Comment by CHJ85** [comment]
I mean, it asks if I want to download the mods after the conversion, which I do.

**Comment by Ekdohibs** [comment]
That's interesting. I'm not sure why it does that, maybe @sofar has a better idea.

**Comment by sofar** [comment]
re-run the `get-mods.sh` script and paste the output, please.

**Comment by CHJ85** [comment]
Okay, so I tried again. Same error.

2019-08-30 05:32:30: WARNING[Main]: BanManager: creating /home/chris/.minetest/worlds/House/ipban.txt
2019-08-30 05:32:31: ERROR[Main]: ModError: Failed to load and run script from /home/chris/.minetest/worlds/House/worldmods/mesecons/init.lua:
2019-08-30 05:32:31: ERROR[Main]: /home/chris/.minetest/worlds/House/worldmods/mesecons/init.lua: No such file or directory

**Comment by sofar** [comment]
I obviously need the output from the `get-mods.sh` script. Not the output from the game after you ran it.

**Comment by CHJ85** [comment]
Yea, sorry. I see what the problem is.
Can't run the script because;
./get-mods.sh: 5: ./get-mods.sh: Syntax error: "(" unexpected
./get-mods.sh: 24: ./get-mods.sh: Bad substitution

**Comment by sofar** [comment]
what is the output of `/bin/sh --version` on your system?

**Comment by CHJ85** [comment]
Illegal option, unfortunately :(
My system is up to date though.
Running Ubuntu 19.04. So I doubt that's the issue.

**Comment by CHJ85** [comment]
Although, the correct way of looking up the version is /bin/bash --version
Mine is version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**Comment by sofar** [comment]
The problem is that the script is a `bash` script. Ubuntu has an incompatible shell

Try:

`/bin/bash get-mods.sh`

**Comment by CHJ85** [comment]
Okay thank you so much.
At last. Here's the output.
There were some errors:

/bin/bash get-mods.sh
Fetching: mesecons
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3473k    0 3473k    0     0  2557k      0 --:--:--  0:00:01 --:--:-- 2557k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: carpet
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2295    0  2295    0     0   4142      0 --:--:-- --:--:-- --:--:--  4135
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: crops
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  486k    0  486k    0     0   498k      0 --:--:-- --:--:-- --:--:--  497k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: flowerpot
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 89855    0 89855    0     0   130k      0 --:--:-- --:--:-- --:--:--  130k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: lapis
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  465k    0  465k    0     0   482k      0 --:--:-- --:--:-- --:--:--  481k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: quartz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  115k    0  115k    0     0   151k      0 --:--:-- --:--:-- --:--:--  151k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: xdecor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  264k    0  264k    0     0   298k      0 --:--:-- --:--:-- --:--:--  297k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: hardenedclay
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9620    0  9620    0     0  17240      0 --:--:-- --:--:-- --:--:-- 17209
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: nether
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   98k    0   98k    0     0   143k      0 --:--:-- --:--:-- --:--:--  143k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: minetest_bedrock
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6878    0  6878    0     0  12643      0 --:--:-- --:--:-- --:--:-- 12620
Fetching: basic_materials
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46463    0 46463    0     0  55777      0 --:--:-- --:--:-- --:--:-- 55711
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: biome_lib
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29629    0 29629    0     0  38629      0 --:--:-- --:--:-- --:--:-- 38579
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: plantlife_modpack
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  798k  100  798k    0     0   651k      0  0:00:01  0:00:01 --:--:--  651k
mv: cannot stat 'minetest_bedrock': No such file or directory
Fetching: signs_lib
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  235k  100  235k    0     0   231k      0  0:00:01  0:00:01 --:--:--  231k
mv: cannot stat 'minetest_bedrock': No such file or directory
Pruning: plantlife_modpack/dryplants
Pruning: plantlife_modpack/along_shore
Pruning: plantlife_modpack/molehills
Pruning: plantlife_modpack/woodsoils
Pruning: plantlife_modpack/bushes
Pruning: plantlife_modpack/bushes_classic
Pruning: plantlife_modpack/youngtrees
Pruning: plantlife_modpack/3dmushrooms
Pruning: plantlife_modpack/cavestuff
Pruning: plantlife_modpack/poisonivy
Pruning: plantlife_modpack/trunks


And here's the game output:
2019-08-30 08:06:08: WARNING[Main]: BanManager: creating /home/chris/.minetest/worlds/House/ipban.txt
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "ferns"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/ferns
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/ferns
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "flowers_plus"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/flowers_plus
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/flowers_plus
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "junglegrass"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/junglegrass
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/junglegrass
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "nature_classic"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/nature_classic
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/nature_classic
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "plantlife_i18n"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_i18n
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/plantlife_i18n
2019-08-30 08:06:08: WARNING[Main]: Mod name conflict detected: "vines"
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/plantlife_modpack-master/vines
2019-08-30 08:06:08: WARNING[Main]: Will not load: /home/chris/.minetest/worlds/House/worldmods/plantlife_modpack/vines
2019-08-30 08:06:08: ERROR[Main]: ModError: Unresolved name conflicts for mods "vines", "flowers_plus", "plantlife_i18n", "ferns", "junglegrass", "nature_classic".

**Comment by Ekdohibs** [comment]
@sofar do you know what the problem might be?

**Comment by sofar** [comment]
@CHJ85 should tell us what map he downloaded so we can reproduce. Otherwise I'm just going to close this issue since there's nothing we can currently do.
