### ISSUE TITLE
Exception on import from 1.15.2

### ISSUE THREAD

**Issue by ndurchx** [minetest-tools/mcimport#30]
When starting the import, an exception occurs and creates an empty world:

```
python3 mcimport.py ... ...
Traceback (most recent call last)::00:14 h:m:s
  File "mcimport.py", line 107, in <module>
    mtmap.save()
  File "/home/dummy/mcimport/block.py", line 455, in save
    for block in self.blocks:
  File "/home/dummy/mcimport/block.py", line 439, in fromMCMapBlocksIterator
    for mcblock in mcmap.getBlocksIterator():
  File "/home/dummy/mcimport/block.py", line 62, in getBlocksIterator
    blocks = self.getChunk(chkx, chkz).blocks
  File "/home/ndurchx/mcimport/block.py", line 45, in getChunk
    return MCChunk(chkx, chkz, self.world_path, self.ext)
  File "/home/dummy/mcimport/block.py", line 91, in __init__
    self.blocks.append(MCBlock(raw_data, (chkx, chkz), section["Y"], True))
  File "/home/dummy/mcimport/block.py", line 108, in __init__
    self.from_section(section)
  File "/home/dummy/mcimport/block.py", line 174, in from_section
    self.blocks = self.reverse_X_axis(section["Blocks"])
KeyError: 'Blocks'
```
Versions: 
Minecraft: 1.15.2 (no mods)
Python: 3.6.9

On some worlds, the exception happens at the first line of the output. On other worlds, after a few correct output lines.
Here is a vanilla map, on which I have the exception at the first line (removed player data):
[MTTest.zip](https://github.com/minetest-tools/mcimport/files/4499978/MTTest.zip)

**Comment by lanegrant** [comment]
I am getting the exact same error.

Minecraft v1.15.2 (no mods)
Python v3.8.2
bash v5.0.16(1)

My output is the same as above. i tried both `./mcimport.sh` and `python3 mcimport.py <input> <output>`

**Comment by jonajames** [comment]
The file save format has been changed in 1.15.
So class MCBlock in block.py cannot convert the data.
I know nothing about Minecraft nor it's save files, I may be able to fix the code but I have no idea what changed in the last version.

https://minecraft.gamepedia.com/Chunk_format

If someone wants to help...

**Comment by alienhunter3010** [comment]
Same problem.
I was trying to convert the Uncensored Library on a pretty fresh Ubuntu 20.04 w/ python 3.8. So I download some old world maps at random. Any convert attempt is ended with the error reported by @ndurchx

**Comment by jonajames** [comment]
I found a python library that is able to extract chunks from MC maps.
https://quarry.readthedocs.io/en/latest/data_types/chunks.html#regions

we could use this library in place of block.py 
I'll try to figure out how.

**Comment by jonajames** [comment]
I ended up completely rewriting the script using that library
Still very rough but at least gives some results
https://github.com/jonajames/mc2mt
